import pandas as pd
from data_types import type_map2
from data_types import columns
import json

### MATCH LABELS 



# PROBLEM! School and Opp_team_id have different style names
# Need them to be identical 

team_labels = {}

# Dictionary of 'school' to 'opp_team_id' key value pairs
team_labels['Abilene Christian Wildcats'] = 'Abilene Christian'
team_labels['Air Force Falcons'] = 'Air Force'
team_labels['Akron Zips'] = 'Akron'
team_labels['Alabama A&M Bulldogs'] = 'Alabama A&M'
team_labels['Alabama Crimson Tide'] = 'Alabama'
team_labels['Alabama State Hornets'] = 'Alabama State'
team_labels['Albany (NY) Great Danes'] = 'Albany (NY)'
team_labels['Alcorn State Braves'] = 'Alcorn State'
team_labels['American Eagles'] = 'American'
team_labels['Appalachian State Mountaineers'] = 'Appalachian State'
team_labels['Arizona State Sun Devils'] = 'Arizona State'
team_labels['Arizona Wildcats'] = 'Arizona'
team_labels['Arkansas Razorbacks'] = 'Arkansas'
team_labels['Arkansas State Red Wolves'] = 'Arkansas State'
team_labels['Arkansas-Pine Bluff Golden Lions'] = 'Arkansas-Pine Bluff'
team_labels['Army Black Knights'] = 'Army'
team_labels['Auburn Tigers'] = 'Auburn'
team_labels['Austin Peay Governors'] = 'Austin Peay'
team_labels['Ball State Cardinals'] = 'Ball State'
team_labels['Baylor Bears'] = 'Baylor'
team_labels['Bellarmine Knights'] = 'Bellarmine'
team_labels['Belmont Bruins'] = 'Belmont'
team_labels['Bethune-Cookman Wildcats'] = 'Bethune-Cookman'
team_labels['Binghamton Bearcats'] = 'Binghamton'
team_labels['Boise State Broncos'] = 'Boise State'
team_labels['Boston College Eagles'] = 'Boston College'
team_labels['Boston University Terriers'] = 'Boston University'
team_labels['Bowling Green State Falcons'] = 'Bowling Green State'
team_labels['Bradley Braves'] = 'Bradley'
team_labels['Brigham Young Cougars'] = 'BYU'
team_labels['Brown Bears'] = 'Brown'
team_labels['Bryant Bulldogs'] = 'Bryant'
team_labels['Bucknell Bison'] = 'Bucknell'
team_labels['Buffalo Bulls'] = 'Buffalo'
team_labels['Butler Bulldogs'] = 'Butler'
team_labels['Cal Poly Mustangs'] = 'Cal Poly'
team_labels['Cal State Bakersfield Roadrunners'] = 'Cal State Bakersfield'
team_labels['Cal State Fullerton Titans'] = 'Cal State Fullerton'
team_labels['Cal State Northridge Matadors'] = 'Cal State Northridge'
team_labels['California Baptist Lancers'] = 'California Baptist'
team_labels['California Golden Bears'] = 'California'
team_labels['Campbell Fighting Camels'] = 'Campbell'
team_labels['Canisius Golden Griffins'] = 'Canisius'
team_labels['Central Arkansas Bears'] = 'Central Arkansas'
team_labels['Central Connecticut State Blue Devils'] = 'Central Connecticut'
team_labels['Central Florida Knights'] = 'UCF'
team_labels['Central Michigan Chippewas'] = 'Central Michigan'
team_labels['Charleston Southern Buccaneers'] = 'Charleston Southern'
team_labels['Charlotte 49ers'] = 'Charlotte'
team_labels['Chattanooga Mocs'] = 'Chattanooga'
team_labels['Chicago State Cougars'] = 'Chicago State'
team_labels['Cincinnati Bearcats'] = 'Cincinnati'
team_labels['Clemson Tigers'] = 'Clemson'
team_labels['Cleveland State Vikings'] = 'Cleveland State'
team_labels['Coastal Carolina Chanticleers'] = 'Coastal Carolina'
team_labels['Colgate Raiders'] = 'Colgate'
team_labels['College of Charleston Cougars'] = 'College of Charleston'
team_labels['Colorado Buffaloes'] = 'Colorado'
team_labels['Colorado State Rams'] = 'Colorado State'
team_labels['Columbia Lions'] = 'Columbia'
team_labels['Connecticut Huskies'] = 'UConn'
team_labels['Coppin State Eagles'] = 'Coppin State'
team_labels['Cornell Big Red'] = 'Cornell'
team_labels['Creighton Bluejays'] = 'Creighton'
team_labels['Dartmouth Big Green'] = 'Dartmouth'
team_labels['Davidson Wildcats'] = 'Davidson'
team_labels['Dayton Flyers'] = 'Dayton'
team_labels['Delaware Fightin\' Blue Hens'] = 'Delaware'
team_labels['Delaware State Hornets'] = 'Delaware State'
team_labels['Denver Pioneers'] = 'Denver'
team_labels['DePaul Blue Demons'] = 'DePaul'
team_labels['Detroit Mercy Titans'] = 'Detroit'
team_labels['Drake Bulldogs'] = 'Drake'
team_labels['Drexel Dragons'] = 'Drexel'
team_labels['Duke Blue Devils'] = 'Duke'
team_labels['Duquesne Dukes'] = 'Duquesne'
team_labels['East Carolina Pirates'] = 'East Carolina'
team_labels['East Tennessee State Buccaneers'] = 'ETSU'
team_labels['Eastern Illinois Panthers'] = 'Eastern Illinois'
team_labels['Eastern Kentucky Colonels'] = 'Eastern Kentucky'
team_labels['Eastern Michigan Eagles'] = 'Eastern Michigan'
team_labels['Eastern Washington Eagles'] = 'Eastern Washington'
team_labels['Elon Phoenix'] = 'Elon'
team_labels['Evansville Purple Aces'] = 'Evansville'
team_labels['Fairfield Stags'] = 'Fairfield'
team_labels['Fairleigh Dickinson Knights'] = 'Fairleigh Dickinson'
team_labels['Florida A&M Rattlers'] = 'Florida A&M'
team_labels['Florida Atlantic Owls'] = 'Florida Atlantic'
team_labels['Florida Gators'] = 'Florida'
team_labels['Florida Gulf Coast Eagles'] = 'Florida Gulf Coast'
team_labels['Florida International Panthers'] = 'Florida International'
team_labels['Florida State Seminoles'] = 'Florida State'
team_labels['Fordham Rams'] = 'Fordham'
team_labels['Fresno State Bulldogs'] = 'Fresno State'
team_labels['Furman Paladins'] = 'Furman'
team_labels['Gardner-Webb Runnin\' Bulldogs'] = 'Gardner-Webb'
team_labels['George Mason Patriots'] = 'George Mason'
team_labels['George Washington Colonials'] = 'George Washington'
team_labels['Georgetown Hoyas'] = 'Georgetown'
team_labels['Georgia Bulldogs'] = 'Georgia'
team_labels['Georgia Southern Eagles'] = 'Georgia Southern'
team_labels['Georgia State Panthers'] = 'Georgia State'
team_labels['Georgia Tech Yellow Jackets'] = 'Georgia Tech'
team_labels['Gonzaga Bulldogs'] = 'Gonzaga'
team_labels['Grambling Tigers'] = 'Grambling'
team_labels['Grand Canyon Antelopes'] = 'Grand Canyon'
team_labels['Green Bay Phoenix'] = 'Green Bay'
team_labels['Hampton Pirates'] = 'Hampton'
team_labels['Hartford Hawks'] = 'Hartford'
team_labels['Harvard Crimson'] = 'Harvard'
team_labels['Hawaii Rainbow Warriors'] = 'Hawaii'
team_labels['High Point Panthers'] = 'High Point'
team_labels['Hofstra Pride'] = 'Hofstra'
team_labels['Holy Cross Crusaders'] = 'Holy Cross'
team_labels['Houston Christian Huskies'] = 'Houston Christian'
team_labels['Houston Cougars'] = 'Houston'
team_labels['Howard Bison'] = 'Howard'
team_labels['Idaho State Bengals'] = 'Idaho State'
team_labels['Idaho Vandals'] = 'Idaho'
team_labels['Illinois Fighting Illini'] = 'Illinois'
team_labels['Illinois State Redbirds'] = 'Illinois State'
team_labels['Illinois-Chicago Flames'] = 'UIC'
team_labels['Incarnate Word Cardinals'] = 'Incarnate Word'
team_labels['Indiana Hoosiers'] = 'Indiana'
team_labels['Indiana State Sycamores'] = 'Indiana State'
team_labels['Iona Gaels'] = 'Iona'
team_labels['Iowa Hawkeyes'] = 'Iowa'
team_labels['Iowa State Cyclones'] = 'Iowa State'
team_labels['IUPUI Jaguars'] = 'IUPUI'
team_labels['Jackson State Tigers'] = 'Jackson State'
team_labels['Jacksonville State Gamecocks'] = 'Jacksonville State'
team_labels['Jacksonville Dolphins'] = 'Jacksonville'
team_labels['James Madison Dukes'] = 'James Madison'
team_labels['Kansas City Roos'] = 'Kansas City'
team_labels['Kansas Jayhawks'] = 'Kansas'
team_labels['Kansas State Wildcats'] = 'Kansas State'
team_labels['Kennesaw State Owls'] = 'Kennesaw State'
team_labels['Kent State Golden Flashes'] = 'Kent State'
team_labels['Kentucky Wildcats'] = 'Kentucky'
team_labels['La Salle Explorers'] = 'La Salle'
team_labels['Lafayette Leopards'] = 'Lafayette'
team_labels['Lamar Cardinals'] = 'Lamar'
team_labels['Lehigh Mountain Hawks'] = 'Lehigh'
team_labels['Liberty Flames'] = 'Liberty'
team_labels['Lindenwood Lions'] = 'Lindenwood'
team_labels['Lipscomb Bisons'] = 'Lipscomb'
team_labels['Little Rock Trojans'] = 'Little Rock'
team_labels['Long Beach State Beach'] = 'Long Beach State'
team_labels['Long Island University Sharks'] = 'LIU'
team_labels['Longwood Lancers'] = 'Longwood'
team_labels['Louisiana Ragin\' Cajuns'] = 'Louisiana'
team_labels['Louisiana State Fighting Tigers'] = 'LSU'
team_labels['Louisiana Tech Bulldogs'] = 'Louisiana Tech'
team_labels['Louisiana-Monroe Warhawks'] = 'Louisiana-Monroe'
team_labels['Louisville Cardinals'] = 'Louisville'
team_labels['Loyola (IL) Ramblers'] = 'Loyola (IL)'
team_labels['Loyola (MD) Greyhounds'] = 'Loyola (MD)'
team_labels['Loyola Marymount Lions'] = 'Loyola Marymount'
team_labels['Maine Black Bears'] = 'Maine'
team_labels['Manhattan Jaspers'] = 'Manhattan'
team_labels['Marist Red Foxes'] = 'Marist'
team_labels['Marquette Golden Eagles'] = 'Marquette'
team_labels['Marshall Thundering Herd'] = 'Marshall'
team_labels['Maryland Terrapins'] = 'Maryland'
team_labels['Maryland-Baltimore County Retrievers'] = 'UMBC'
team_labels['Maryland-Eastern Shore Hawks'] = 'Maryland-Eastern Shore'
team_labels['Massachusetts Minutemen'] = 'UMass'
team_labels['Massachusetts-Lowell River Hawks'] = 'UMass-Lowell'
team_labels['McNeese State Cowboys'] = 'McNeese State'
team_labels['Memphis Tigers'] = 'Memphis'
team_labels['Mercer Bears'] = 'Mercer'
team_labels['Merrimack Warriors'] = 'Merrimack'
team_labels['Miami (FL) Hurricanes'] = 'Miami (FL)'
team_labels['Miami (OH) RedHawks'] = 'Miami (OH)'
team_labels['Michigan State Spartans'] = 'Michigan State'
team_labels['Michigan Wolverines'] = 'Michigan'
team_labels['Middle Tennessee Blue Raiders'] = 'Middle Tennessee'
team_labels['Milwaukee Panthers'] = 'Milwaukee'
team_labels['Minnesota Golden Gophers'] = 'Minnesota'
team_labels['Mississippi Rebels'] = 'Ole Miss'
team_labels['Mississippi State Bulldogs'] = 'Mississippi State'
team_labels['Mississippi Valley State Delta Devils'] = 'Mississippi Valley State'
team_labels['Missouri State Bears'] = 'Missouri State'
team_labels['Missouri Tigers'] = 'Missouri'
team_labels['Monmouth Hawks'] = 'Monmouth'
team_labels['Montana Grizzlies'] = 'Montana'
team_labels['Montana State Bobcats'] = 'Montana State'
team_labels['Morehead State Eagles'] = 'Morehead State'
team_labels['Morgan State Bears'] = 'Morgan State'
team_labels['Mount St. Mary\'s Mountaineers'] = 'Mount St. Mary\'s'
team_labels['Murray State Racers'] = 'Murray State'
team_labels['Navy Midshipmen'] = 'Navy'
team_labels['NC State Wolfpack'] = 'NC State'
team_labels['Nebraska Cornhuskers'] = 'Nebraska'
team_labels['Nevada Wolf Pack'] = 'Nevada'
team_labels['Nevada-Las Vegas Rebels'] = 'UNLV'
team_labels['New Hampshire Wildcats'] = 'New Hampshire'
team_labels['New Mexico Lobos'] = 'New Mexico'
team_labels['New Mexico State Aggies'] = 'New Mexico State'
team_labels['New Orleans Privateers'] = 'New Orleans'
team_labels['Niagara Purple Eagles'] = 'Niagara'
team_labels['Nicholls State Colonels'] = 'Nicholls State'
team_labels['NJIT Highlanders'] = 'NJIT'
team_labels['Norfolk State Spartans'] = 'Norfolk State'
team_labels['North Alabama Lions'] = 'North Alabama'
team_labels['North Carolina A&T Aggies'] = 'North Carolina A&T'
team_labels['North Carolina Central Eagles'] = 'North Carolina Central'
team_labels['North Carolina Tar Heels'] = 'UNC'
team_labels['North Dakota Fighting Hawks'] = 'North Dakota'
team_labels['North Dakota State Bison'] = 'North Dakota State'
team_labels['North Florida Ospreys'] = 'North Florida'
team_labels['North Texas Mean Green'] = 'North Texas'
team_labels['Northeastern Huskies'] = 'Northeastern'
team_labels['Northern Arizona Lumberjacks'] = 'Northern Arizona'
team_labels['Northern Colorado Bears'] = 'Northern Colorado'
team_labels['Northern Illinois Huskies'] = 'Northern Illinois'
team_labels['Northern Iowa Panthers'] = 'Northern Iowa'
team_labels['Northern Kentucky Norse'] = 'Northern Kentucky'
team_labels['Northwestern State Demons'] = 'Northwestern State'
team_labels['Northwestern Wildcats'] = 'Northwestern'
team_labels['Notre Dame Fighting Irish'] = 'Notre Dame'
team_labels['Oakland Golden Grizzlies'] = 'Oakland'
team_labels['Ohio Bobcats'] = 'Ohio'
team_labels['Ohio State Buckeyes'] = 'Ohio State'
team_labels['Oklahoma Sooners'] = 'Oklahoma'
team_labels['Oklahoma State Cowboys'] = 'Oklahoma State'
team_labels['Old Dominion Monarchs'] = 'Old Dominion'
team_labels['Omaha Mavericks'] = 'Omaha'
team_labels['Oral Roberts Golden Eagles'] = 'Oral Roberts'
team_labels['Oregon Ducks'] = 'Oregon'
team_labels['Oregon State Beavers'] = 'Oregon State'
team_labels['Pacific Tigers'] = 'Pacific'
team_labels['Penn State Nittany Lions'] = 'Penn State'
team_labels['Pennsylvania Quakers'] = 'Penn'
team_labels['Pepperdine Waves'] = 'Pepperdine'
team_labels['Pittsburgh Panthers'] = 'Pitt'
team_labels['Portland Pilots'] = 'Portland'
team_labels['Portland State Vikings'] = 'Portland State'
team_labels['Prairie View Panthers'] = 'Prairie View'
team_labels['Presbyterian Blue Hose'] = 'Presbyterian'
team_labels['Princeton Tigers'] = 'Princeton'
team_labels['Providence Friars'] = 'Providence'
team_labels['Purdue Boilermakers'] = 'Purdue'
team_labels['Purdue-Fort Wayne Mastodons'] = 'Purdue-Fort Wayne'
team_labels['Queens (NC) Royals'] = 'Queens (NC)'
team_labels['Quinnipiac Bobcats'] = 'Quinnipiac'
team_labels['Radford Highlanders'] = 'Radford'
team_labels['Rhode Island Rams'] = 'Rhode Island'
team_labels['Rice Owls'] = 'Rice'
team_labels['Richmond Spiders'] = 'Richmond'
team_labels['Rider Broncs'] = 'Rider'
team_labels['Robert Morris Colonials'] = 'Robert Morris'
team_labels['Rutgers Scarlet Knights'] = 'Rutgers'
team_labels['Sacramento State Hornets'] = 'Sacramento State'
team_labels['Sacred Heart Pioneers'] = 'Sacred Heart'
team_labels['Saint Francis (PA) Red Flash'] = 'Saint Francis (PA)'
team_labels['Saint Joseph\'s Hawks'] = 'St. Joseph\'s'
team_labels['Saint Louis Billikens'] = 'Saint Louis'
team_labels['Saint Mary\'s (CA) Gaels'] = 'Saint Mary\'s'
team_labels['Saint Peter\'s Peacocks'] = 'St. Peter\'s'
team_labels['Sam Houston State Bearkats'] = 'Sam Houston State'
team_labels['Samford Bulldogs'] = 'Samford'
team_labels['San Diego State Aztecs'] = 'San Diego State'
team_labels['San Diego Toreros'] = 'San Diego'
team_labels['San Francisco Dons'] = 'San Francisco'
team_labels['San Jose State Spartans'] = 'San Jose State'
team_labels['Santa Clara Broncos'] = 'Santa Clara'
team_labels['Seattle Redhawks'] = 'Seattle'
team_labels['Seton Hall Pirates'] = 'Seton Hall'
team_labels['Siena Saints'] = 'Siena'
team_labels['South Alabama Jaguars'] = 'South Alabama'
team_labels['South Carolina Gamecocks'] = 'South Carolina'
team_labels['South Carolina State Bulldogs'] = 'South Carolina State'
team_labels['South Carolina Upstate Spartans'] = 'USC Upstate'
team_labels['South Dakota Coyotes'] = 'South Dakota'
team_labels['South Dakota State Jackrabbits'] = 'South Dakota State'
team_labels['South Florida Bulls'] = 'South Florida'
team_labels['Southeast Missouri State Redhawks'] = 'Southeast Missouri State'
team_labels['Southeastern Louisiana Lions'] = 'Southeastern Louisiana'
team_labels['Southern California Trojans'] = 'USC'
team_labels['Southern Illinois Salukis'] = 'Southern Illinois'
team_labels['Southern Illinois-Edwardsville Cougars'] = 'SIU-Edwardsville'
team_labels['Southern Indiana Screaming Eagles'] = 'Southern Indiana'
team_labels['Southern Jaguars'] = 'Southern'
team_labels['Southern Methodist Mustangs'] = 'SMU'
team_labels['Southern Mississippi Golden Eagles'] = 'Southern Miss'
team_labels['Southern Utah Thunderbirds'] = 'Southern Utah'
team_labels['St. Bonaventure Bonnies'] = 'St. Bonaventure'
team_labels['St. Francis (NY) Terriers'] = 'St. Francis (NY)'
team_labels['St. John\'s (NY) Red Storm'] = 'St. John\'s (NY)'
team_labels['St. Thomas Tommies'] = 'St. Thomas'
team_labels['Stanford Cardinal'] = 'Stanford'
team_labels['Stephen F. Austin Lumberjacks'] = 'Stephen F. Austin'
team_labels['Stetson Hatters'] = 'Stetson'
team_labels['Stonehill Skyhawks'] = 'Stonehill'
team_labels['Stony Brook Seawolves'] = 'Stony Brook'
team_labels['Syracuse Orange'] = 'Syracuse'
team_labels['Tarleton State Texans'] = 'Tarleton State'
team_labels['TCU Horned Frogs'] = 'TCU'
team_labels['Temple Owls'] = 'Temple'
team_labels['Tennessee State Tigers'] = 'Tennessee State'
team_labels['Tennessee Tech Golden Eagles'] = 'Tennessee Tech'
team_labels['Tennessee Volunteers'] = 'Tennessee'
team_labels['Tennessee-Martin Skyhawks'] = 'UT-Martin'
team_labels['Texas A&M Aggies'] = 'Texas A&M'
team_labels['Texas A&M-Commerce Lions'] = 'Texas A&M-Commerce'
team_labels['Texas A&M-Corpus Christi Islanders'] = 'Texas A&M-Corpus Christi'
team_labels['Texas Longhorns'] = 'Texas'
team_labels['Texas Southern Tigers'] = 'Texas Southern'
team_labels['Texas State Bobcats'] = 'Texas State'
team_labels['Texas Tech Red Raiders'] = 'Texas Tech'
team_labels['Texas-Rio Grande Valley Vaqueros'] = 'Texas-Rio Grande Valley'
team_labels['The Citadel Bulldogs'] = 'The Citadel'
team_labels['Toledo Rockets'] = 'Toledo'
team_labels['Towson Tigers'] = 'Towson'
team_labels['Troy Trojans'] = 'Troy'
team_labels['Tulane Green Wave'] = 'Tulane'
team_labels['Tulsa Golden Hurricane'] = 'Tulsa'
team_labels['UAB Blazers'] = 'UAB'
team_labels['UC Davis Aggies'] = 'UC-Davis'
team_labels['UC Irvine Anteaters'] = 'UC-Irvine'
team_labels['UC Riverside Highlanders'] = 'UC-Riverside'
team_labels['UC San Diego Tritons'] = 'UC-San Diego'
team_labels['UC Santa Barbara Gauchos'] = 'UCSB'
team_labels['UCLA Bruins'] = 'UCLA'
team_labels['UNC Asheville Bulldogs'] = 'UNC Asheville'
team_labels['UNC Greensboro Spartans'] = 'UNC Greensboro'
team_labels['UNC Wilmington Seahawks'] = 'UNC Wilmington'
team_labels['UT Arlington Mavericks'] = 'UT Arlington'
team_labels['Utah State Aggies'] = 'Utah State'
team_labels['Utah Tech Trailblazers'] = 'Utah Tech'
team_labels['Utah Utes'] = 'Utah'
team_labels['Utah Valley Wolverines'] = 'Utah Valley'
team_labels['UTEP Miners'] = 'UTEP'
team_labels['UTSA Roadrunners'] = 'UTSA'
team_labels['Valparaiso Beacons'] = 'Valparaiso'
team_labels['Vanderbilt Commodores'] = 'Vanderbilt'
team_labels['Vermont Catamounts'] = 'Vermont'
team_labels['Villanova Wildcats'] = 'Villanova'
team_labels['Virginia Cavaliers'] = 'Virginia'
team_labels['Virginia Commonwealth Rams'] = 'VCU'
team_labels['Virginia Military Institute Keydets'] = 'VMI'
team_labels['Virginia Tech Hokies'] = 'Virginia Tech'
team_labels['Wagner Seahawks'] = 'Wagner'
team_labels['Wake Forest Demon Deacons'] = 'Wake Forest'
team_labels['Washington Huskies'] = 'Washington'
team_labels['Washington State Cougars'] = 'Washington State'
team_labels['Weber State Wildcats'] = 'Weber State'
team_labels['West Virginia Mountaineers'] = 'West Virginia'
team_labels['Western Carolina Catamounts'] = 'Western Carolina'
team_labels['Western Illinois Leathernecks'] = 'Western Illinois'
team_labels['Western Kentucky Hilltoppers'] = 'Western Kentucky'
team_labels['Western Michigan Broncos'] = 'Western Michigan'
team_labels['Wichita State Shockers'] = 'Wichita State'
team_labels['William & Mary Tribe'] = 'William & Mary'
team_labels['Winthrop Eagles'] = 'Winthrop'
team_labels['Wisconsin Badgers'] = 'Wisconsin'
team_labels['Wofford Terriers'] = 'Wofford'
team_labels['Wright State Raiders'] = 'Wright State'
team_labels['Wyoming Cowboys'] = 'Wyoming'
team_labels['Xavier Musketeers'] = 'Xavier'
team_labels['Yale Bulldogs'] = 'Yale'  
team_labels['Youngstown State Penguins'] = 'Youngstown State'

# import difflib 

def match_labels(df):
    """
    Input dataframe, get back data frame where 'school' column label format matches 'opp_team_id' column label format

    :param - df 
    :return - df with consistent school labels
    """

    team_labels = {}
    # cut = 0.8

    # empty_values_exist = True # set a value for while loop to go
    # while empty_values_exist:
    #     if cut <= 0.1: # create a catch safe, so cut doesn't go below zero in case there are empty 
    #         break
    #     for name in df['school'].unique(): 
    #         if name not in team_labels: # if the dictionary does not already have the key
    #             try:
    #                 team_labels[name] = difflib.get_close_matches(name, df['opp_team_id'].unique(), n = 1, cutoff=cut)[0] # try get the key
    #             except IndexError: 
    #                 continue # if the function produces no matches, go to the next one

    #     cut -= 0.1 # after looping through, reduce the cutoff parameter by one
    


    # Dictionary of 'school' to 'opp_team_id' key value pairs
    team_labels['Abilene Christian Wildcats'] = 'Abilene Christian'
    team_labels['Air Force Falcons'] = 'Air Force'
    team_labels['Akron Zips'] = 'Akron'
    team_labels['Alabama A&M Bulldogs'] = 'Alabama A&M'
    team_labels['Alabama Crimson Tide'] = 'Alabama'
    team_labels['Alabama State Hornets'] = 'Alabama State'
    team_labels['Albany (NY) Great Danes'] = 'Albany (NY)'
    team_labels['Alcorn State Braves'] = 'Alcorn State'
    team_labels['American Eagles'] = 'American'
    team_labels['Appalachian State Mountaineers'] = 'Appalachian State'
    team_labels['Arizona State Sun Devils'] = 'Arizona State'
    team_labels['Arizona Wildcats'] = 'Arizona'
    team_labels['Arkansas Razorbacks'] = 'Arkansas'
    team_labels['Arkansas State Red Wolves'] = 'Arkansas State'
    team_labels['Arkansas-Pine Bluff Golden Lions'] = 'Arkansas-Pine Bluff'
    team_labels['Army Black Knights'] = 'Army'
    team_labels['Auburn Tigers'] = 'Auburn'
    team_labels['Austin Peay Governors'] = 'Austin Peay'
    team_labels['Ball State Cardinals'] = 'Ball State'
    team_labels['Baylor Bears'] = 'Baylor'
    team_labels['Bellarmine Knights'] = 'Bellarmine'
    team_labels['Belmont Bruins'] = 'Belmont'
    team_labels['Bethune-Cookman Wildcats'] = 'Bethune-Cookman'
    team_labels['Binghamton Bearcats'] = 'Binghamton'
    team_labels['Boise State Broncos'] = 'Boise State'
    team_labels['Boston College Eagles'] = 'Boston College'
    team_labels['Boston University Terriers'] = 'Boston University'
    team_labels['Bowling Green State Falcons'] = 'Bowling Green State'
    team_labels['Bradley Braves'] = 'Bradley'
    team_labels['Brigham Young Cougars'] = 'BYU'
    team_labels['Brown Bears'] = 'Brown'
    team_labels['Bryant Bulldogs'] = 'Bryant'
    team_labels['Bucknell Bison'] = 'Bucknell'
    team_labels['Buffalo Bulls'] = 'Buffalo'
    team_labels['Butler Bulldogs'] = 'Butler'
    team_labels['Cal Poly Mustangs'] = 'Cal Poly'
    team_labels['Cal State Bakersfield Roadrunners'] = 'Cal State Bakersfield'
    team_labels['Cal State Fullerton Titans'] = 'Cal State Fullerton'
    team_labels['Cal State Northridge Matadors'] = 'Cal State Northridge'
    team_labels['California Baptist Lancers'] = 'California Baptist'
    team_labels['California Golden Bears'] = 'California'
    team_labels['Campbell Fighting Camels'] = 'Campbell'
    team_labels['Canisius Golden Griffins'] = 'Canisius'
    team_labels['Central Arkansas Bears'] = 'Central Arkansas'
    team_labels['Central Connecticut State Blue Devils'] = 'Central Connecticut'
    team_labels['Central Florida Knights'] = 'UCF'
    team_labels['Central Michigan Chippewas'] = 'Central Michigan'
    team_labels['Charleston Southern Buccaneers'] = 'Charleston Southern'
    team_labels['Charlotte 49ers'] = 'Charlotte'
    team_labels['Chattanooga Mocs'] = 'Chattanooga'
    team_labels['Chicago State Cougars'] = 'Chicago State'
    team_labels['Cincinnati Bearcats'] = 'Cincinnati'
    team_labels['Clemson Tigers'] = 'Clemson'
    team_labels['Cleveland State Vikings'] = 'Cleveland State'
    team_labels['Coastal Carolina Chanticleers'] = 'Coastal Carolina'
    team_labels['Colgate Raiders'] = 'Colgate'
    team_labels['College of Charleston Cougars'] = 'College of Charleston'
    team_labels['Colorado Buffaloes'] = 'Colorado'
    team_labels['Colorado State Rams'] = 'Colorado State'
    team_labels['Columbia Lions'] = 'Columbia'
    team_labels['Connecticut Huskies'] = 'UConn'
    team_labels['Coppin State Eagles'] = 'Coppin State'
    team_labels['Cornell Big Red'] = 'Cornell'
    team_labels['Creighton Bluejays'] = 'Creighton'
    team_labels['Dartmouth Big Green'] = 'Dartmouth'
    team_labels['Davidson Wildcats'] = 'Davidson'
    team_labels['Dayton Flyers'] = 'Dayton'
    team_labels['Delaware Fightin\' Blue Hens'] = 'Delaware'
    team_labels['Delaware State Hornets'] = 'Delaware State'
    team_labels['Denver Pioneers'] = 'Denver'
    team_labels['DePaul Blue Demons'] = 'DePaul'
    team_labels['Detroit Mercy Titans'] = 'Detroit'
    team_labels['Drake Bulldogs'] = 'Drake'
    team_labels['Drexel Dragons'] = 'Drexel'
    team_labels['Duke Blue Devils'] = 'Duke'
    team_labels['Duquesne Dukes'] = 'Duquesne'
    team_labels['East Carolina Pirates'] = 'East Carolina'
    team_labels['East Tennessee State Buccaneers'] = 'ETSU'
    team_labels['Eastern Illinois Panthers'] = 'Eastern Illinois'
    team_labels['Eastern Kentucky Colonels'] = 'Eastern Kentucky'
    team_labels['Eastern Michigan Eagles'] = 'Eastern Michigan'
    team_labels['Eastern Washington Eagles'] = 'Eastern Washington'
    team_labels['Elon Phoenix'] = 'Elon'
    team_labels['Evansville Purple Aces'] = 'Evansville'
    team_labels['Fairfield Stags'] = 'Fairfield'
    team_labels['Fairleigh Dickinson Knights'] = 'Fairleigh Dickinson'
    team_labels['Florida A&M Rattlers'] = 'Florida A&M'
    team_labels['Florida Atlantic Owls'] = 'Florida Atlantic'
    team_labels['Florida Gators'] = 'Florida'
    team_labels['Florida Gulf Coast Eagles'] = 'Florida Gulf Coast'
    team_labels['Florida International Panthers'] = 'Florida International'
    team_labels['Florida State Seminoles'] = 'Florida State'
    team_labels['Fordham Rams'] = 'Fordham'
    team_labels['Fresno State Bulldogs'] = 'Fresno State'
    team_labels['Furman Paladins'] = 'Furman'
    team_labels['Gardner-Webb Runnin\' Bulldogs'] = 'Gardner-Webb'
    team_labels['George Mason Patriots'] = 'George Mason'
    team_labels['George Washington Colonials'] = 'George Washington'
    team_labels['Georgetown Hoyas'] = 'Georgetown'
    team_labels['Georgia Bulldogs'] = 'Georgia'
    team_labels['Georgia Southern Eagles'] = 'Georgia Southern'
    team_labels['Georgia State Panthers'] = 'Georgia State'
    team_labels['Georgia Tech Yellow Jackets'] = 'Georgia Tech'
    team_labels['Gonzaga Bulldogs'] = 'Gonzaga'
    team_labels['Grambling Tigers'] = 'Grambling'
    team_labels['Grand Canyon Antelopes'] = 'Grand Canyon'
    team_labels['Green Bay Phoenix'] = 'Green Bay'
    team_labels['Hampton Pirates'] = 'Hampton'
    team_labels['Hartford Hawks'] = 'Hartford'
    team_labels['Harvard Crimson'] = 'Harvard'
    team_labels['Hawaii Rainbow Warriors'] = 'Hawaii'
    team_labels['High Point Panthers'] = 'High Point'
    team_labels['Hofstra Pride'] = 'Hofstra'
    team_labels['Holy Cross Crusaders'] = 'Holy Cross'
    team_labels['Houston Christian Huskies'] = 'Houston Christian'
    team_labels['Houston Cougars'] = 'Houston'
    team_labels['Howard Bison'] = 'Howard'
    team_labels['Idaho State Bengals'] = 'Idaho State'
    team_labels['Idaho Vandals'] = 'Idaho'
    team_labels['Illinois Fighting Illini'] = 'Illinois'
    team_labels['Illinois State Redbirds'] = 'Illinois State'
    team_labels['Illinois-Chicago Flames'] = 'UIC'
    team_labels['Incarnate Word Cardinals'] = 'Incarnate Word'
    team_labels['Indiana Hoosiers'] = 'Indiana'
    team_labels['Indiana State Sycamores'] = 'Indiana State'
    team_labels['Iona Gaels'] = 'Iona'
    team_labels['Iowa Hawkeyes'] = 'Iowa'
    team_labels['Iowa State Cyclones'] = 'Iowa State'
    team_labels['IUPUI Jaguars'] = 'IUPUI'
    team_labels['Jackson State Tigers'] = 'Jackson State'
    team_labels['Jacksonville State Gamecocks'] = 'Jacksonville State'
    team_labels['Jacksonville Dolphins'] = 'Jacksonville'
    team_labels['James Madison Dukes'] = 'James Madison'
    team_labels['Kansas City Roos'] = 'Kansas City'
    team_labels['Kansas Jayhawks'] = 'Kansas'
    team_labels['Kansas State Wildcats'] = 'Kansas State'
    team_labels['Kennesaw State Owls'] = 'Kennesaw State'
    team_labels['Kent State Golden Flashes'] = 'Kent State'
    team_labels['Kentucky Wildcats'] = 'Kentucky'
    team_labels['La Salle Explorers'] = 'La Salle'
    team_labels['Lafayette Leopards'] = 'Lafayette'
    team_labels['Lamar Cardinals'] = 'Lamar'
    team_labels['Lehigh Mountain Hawks'] = 'Lehigh'
    team_labels['Liberty Flames'] = 'Liberty'
    team_labels['Lindenwood Lions'] = 'Lindenwood'
    team_labels['Lipscomb Bisons'] = 'Lipscomb'
    team_labels['Little Rock Trojans'] = 'Little Rock'
    team_labels['Long Beach State Beach'] = 'Long Beach State'
    team_labels['Long Island University Sharks'] = 'LIU'
    team_labels['Longwood Lancers'] = 'Longwood'
    team_labels['Louisiana Ragin\' Cajuns'] = 'Louisiana'
    team_labels['Louisiana State Fighting Tigers'] = 'LSU'
    team_labels['Louisiana Tech Bulldogs'] = 'Louisiana Tech'
    team_labels['Louisiana-Monroe Warhawks'] = 'Louisiana-Monroe'
    team_labels['Louisville Cardinals'] = 'Louisville'
    team_labels['Loyola (IL) Ramblers'] = 'Loyola (IL)'
    team_labels['Loyola (MD) Greyhounds'] = 'Loyola (MD)'
    team_labels['Loyola Marymount Lions'] = 'Loyola Marymount'
    team_labels['Maine Black Bears'] = 'Maine'
    team_labels['Manhattan Jaspers'] = 'Manhattan'
    team_labels['Marist Red Foxes'] = 'Marist'
    team_labels['Marquette Golden Eagles'] = 'Marquette'
    team_labels['Marshall Thundering Herd'] = 'Marshall'
    team_labels['Maryland Terrapins'] = 'Maryland'
    team_labels['Maryland-Baltimore County Retrievers'] = 'UMBC'
    team_labels['Maryland-Eastern Shore Hawks'] = 'Maryland-Eastern Shore'
    team_labels['Massachusetts Minutemen'] = 'UMass'
    team_labels['Massachusetts-Lowell River Hawks'] = 'UMass-Lowell'
    team_labels['McNeese State Cowboys'] = 'McNeese State'
    team_labels['Memphis Tigers'] = 'Memphis'
    team_labels['Mercer Bears'] = 'Mercer'
    team_labels['Merrimack Warriors'] = 'Merrimack'
    team_labels['Miami (FL) Hurricanes'] = 'Miami (FL)'
    team_labels['Miami (OH) RedHawks'] = 'Miami (OH)'
    team_labels['Michigan State Spartans'] = 'Michigan State'
    team_labels['Michigan Wolverines'] = 'Michigan'
    team_labels['Middle Tennessee Blue Raiders'] = 'Middle Tennessee'
    team_labels['Milwaukee Panthers'] = 'Milwaukee'
    team_labels['Minnesota Golden Gophers'] = 'Minnesota'
    team_labels['Mississippi Rebels'] = 'Ole Miss'
    team_labels['Mississippi State Bulldogs'] = 'Mississippi State'
    team_labels['Mississippi Valley State Delta Devils'] = 'Mississippi Valley State'
    team_labels['Missouri State Bears'] = 'Missouri State'
    team_labels['Missouri Tigers'] = 'Missouri'
    team_labels['Monmouth Hawks'] = 'Monmouth'
    team_labels['Montana Grizzlies'] = 'Montana'
    team_labels['Montana State Bobcats'] = 'Montana State'
    team_labels['Morehead State Eagles'] = 'Morehead State'
    team_labels['Morgan State Bears'] = 'Morgan State'
    team_labels['Mount St. Mary\'s Mountaineers'] = 'Mount St. Mary\'s'
    team_labels['Murray State Racers'] = 'Murray State'
    team_labels['Navy Midshipmen'] = 'Navy'
    team_labels['NC State Wolfpack'] = 'NC State'
    team_labels['Nebraska Cornhuskers'] = 'Nebraska'
    team_labels['Nevada Wolf Pack'] = 'Nevada'
    team_labels['Nevada-Las Vegas Rebels'] = 'UNLV'
    team_labels['New Hampshire Wildcats'] = 'New Hampshire'
    team_labels['New Mexico Lobos'] = 'New Mexico'
    team_labels['New Mexico State Aggies'] = 'New Mexico State'
    team_labels['New Orleans Privateers'] = 'New Orleans'
    team_labels['Niagara Purple Eagles'] = 'Niagara'
    team_labels['Nicholls State Colonels'] = 'Nicholls State'
    team_labels['NJIT Highlanders'] = 'NJIT'
    team_labels['Norfolk State Spartans'] = 'Norfolk State'
    team_labels['North Alabama Lions'] = 'North Alabama'
    team_labels['North Carolina A&T Aggies'] = 'North Carolina A&T'
    team_labels['North Carolina Central Eagles'] = 'North Carolina Central'
    team_labels['North Carolina Tar Heels'] = 'UNC'
    team_labels['North Dakota Fighting Hawks'] = 'North Dakota'
    team_labels['North Dakota State Bison'] = 'North Dakota State'
    team_labels['North Florida Ospreys'] = 'North Florida'
    team_labels['North Texas Mean Green'] = 'North Texas'
    team_labels['Northeastern Huskies'] = 'Northeastern'
    team_labels['Northern Arizona Lumberjacks'] = 'Northern Arizona'
    team_labels['Northern Colorado Bears'] = 'Northern Colorado'
    team_labels['Northern Illinois Huskies'] = 'Northern Illinois'
    team_labels['Northern Iowa Panthers'] = 'Northern Iowa'
    team_labels['Northern Kentucky Norse'] = 'Northern Kentucky'
    team_labels['Northwestern State Demons'] = 'Northwestern State'
    team_labels['Northwestern Wildcats'] = 'Northwestern'
    team_labels['Notre Dame Fighting Irish'] = 'Notre Dame'
    team_labels['Oakland Golden Grizzlies'] = 'Oakland'
    team_labels['Ohio Bobcats'] = 'Ohio'
    team_labels['Ohio State Buckeyes'] = 'Ohio State'
    team_labels['Oklahoma Sooners'] = 'Oklahoma'
    team_labels['Oklahoma State Cowboys'] = 'Oklahoma State'
    team_labels['Old Dominion Monarchs'] = 'Old Dominion'
    team_labels['Omaha Mavericks'] = 'Omaha'
    team_labels['Oral Roberts Golden Eagles'] = 'Oral Roberts'
    team_labels['Oregon Ducks'] = 'Oregon'
    team_labels['Oregon State Beavers'] = 'Oregon State'
    team_labels['Pacific Tigers'] = 'Pacific'
    team_labels['Penn State Nittany Lions'] = 'Penn State'
    team_labels['Pennsylvania Quakers'] = 'Penn'
    team_labels['Pepperdine Waves'] = 'Pepperdine'
    team_labels['Pittsburgh Panthers'] = 'Pitt'
    team_labels['Portland Pilots'] = 'Portland'
    team_labels['Portland State Vikings'] = 'Portland State'
    team_labels['Prairie View Panthers'] = 'Prairie View'
    team_labels['Presbyterian Blue Hose'] = 'Presbyterian'
    team_labels['Princeton Tigers'] = 'Princeton'
    team_labels['Providence Friars'] = 'Providence'
    team_labels['Purdue Boilermakers'] = 'Purdue'
    team_labels['Purdue-Fort Wayne Mastodons'] = 'Purdue-Fort Wayne'
    team_labels['Queens (NC) Royals'] = 'Queens (NC)'
    team_labels['Quinnipiac Bobcats'] = 'Quinnipiac'
    team_labels['Radford Highlanders'] = 'Radford'
    team_labels['Rhode Island Rams'] = 'Rhode Island'
    team_labels['Rice Owls'] = 'Rice'
    team_labels['Richmond Spiders'] = 'Richmond'
    team_labels['Rider Broncs'] = 'Rider'
    team_labels['Robert Morris Colonials'] = 'Robert Morris'
    team_labels['Rutgers Scarlet Knights'] = 'Rutgers'
    team_labels['Sacramento State Hornets'] = 'Sacramento State'
    team_labels['Sacred Heart Pioneers'] = 'Sacred Heart'
    team_labels['Saint Francis (PA) Red Flash'] = 'Saint Francis (PA)'
    team_labels['Saint Joseph\'s Hawks'] = 'St. Joseph\'s'
    team_labels['Saint Louis Billikens'] = 'Saint Louis'
    team_labels['Saint Mary\'s (CA) Gaels'] = 'Saint Mary\'s'
    team_labels['Saint Peter\'s Peacocks'] = 'St. Peter\'s'
    team_labels['Sam Houston State Bearkats'] = 'Sam Houston State'
    team_labels['Samford Bulldogs'] = 'Samford'
    team_labels['San Diego State Aztecs'] = 'San Diego State'
    team_labels['San Diego Toreros'] = 'San Diego'
    team_labels['San Francisco Dons'] = 'San Francisco'
    team_labels['San Jose State Spartans'] = 'San Jose State'
    team_labels['Santa Clara Broncos'] = 'Santa Clara'
    team_labels['Seattle Redhawks'] = 'Seattle'
    team_labels['Seton Hall Pirates'] = 'Seton Hall'
    team_labels['Siena Saints'] = 'Siena'
    team_labels['South Alabama Jaguars'] = 'South Alabama'
    team_labels['South Carolina Gamecocks'] = 'South Carolina'
    team_labels['South Carolina State Bulldogs'] = 'South Carolina State'
    team_labels['South Carolina Upstate Spartans'] = 'USC Upstate'
    team_labels['South Dakota Coyotes'] = 'South Dakota'
    team_labels['South Dakota State Jackrabbits'] = 'South Dakota State'
    team_labels['South Florida Bulls'] = 'South Florida'
    team_labels['Southeast Missouri State Redhawks'] = 'Southeast Missouri State'
    team_labels['Southeastern Louisiana Lions'] = 'Southeastern Louisiana'
    team_labels['Southern California Trojans'] = 'USC'
    team_labels['Southern Illinois Salukis'] = 'Southern Illinois'
    team_labels['Southern Illinois-Edwardsville Cougars'] = 'SIU-Edwardsville'
    team_labels['Southern Indiana Screaming Eagles'] = 'Southern Indiana'
    team_labels['Southern Jaguars'] = 'Southern'
    team_labels['Southern Methodist Mustangs'] = 'SMU'
    team_labels['Southern Mississippi Golden Eagles'] = 'Southern Miss'
    team_labels['Southern Utah Thunderbirds'] = 'Southern Utah'
    team_labels['St. Bonaventure Bonnies'] = 'St. Bonaventure'
    team_labels['St. Francis (NY) Terriers'] = 'St. Francis (NY)'
    team_labels['St. John\'s (NY) Red Storm'] = 'St. John\'s (NY)'
    team_labels['St. Thomas Tommies'] = 'St. Thomas'
    team_labels['Stanford Cardinal'] = 'Stanford'
    team_labels['Stephen F. Austin Lumberjacks'] = 'Stephen F. Austin'
    team_labels['Stetson Hatters'] = 'Stetson'
    team_labels['Stonehill Skyhawks'] = 'Stonehill'
    team_labels['Stony Brook Seawolves'] = 'Stony Brook'
    team_labels['Syracuse Orange'] = 'Syracuse'
    team_labels['Tarleton State Texans'] = 'Tarleton State'
    team_labels['TCU Horned Frogs'] = 'TCU'
    team_labels['Temple Owls'] = 'Temple'
    team_labels['Tennessee State Tigers'] = 'Tennessee State'
    team_labels['Tennessee Tech Golden Eagles'] = 'Tennessee Tech'
    team_labels['Tennessee Volunteers'] = 'Tennessee'
    team_labels['Tennessee-Martin Skyhawks'] = 'UT-Martin'
    team_labels['Texas A&M Aggies'] = 'Texas A&M'
    team_labels['Texas A&M-Commerce Lions'] = 'Texas A&M-Commerce'
    team_labels['Texas A&M-Corpus Christi Islanders'] = 'Texas A&M-Corpus Christi'
    team_labels['Texas Longhorns'] = 'Texas'
    team_labels['Texas Southern Tigers'] = 'Texas Southern'
    team_labels['Texas State Bobcats'] = 'Texas State'
    team_labels['Texas Tech Red Raiders'] = 'Texas Tech'
    team_labels['Texas-Rio Grande Valley Vaqueros'] = 'Texas-Rio Grande Valley'
    team_labels['The Citadel Bulldogs'] = 'The Citadel'
    team_labels['Toledo Rockets'] = 'Toledo'
    team_labels['Towson Tigers'] = 'Towson'
    team_labels['Troy Trojans'] = 'Troy'
    team_labels['Tulane Green Wave'] = 'Tulane'
    team_labels['Tulsa Golden Hurricane'] = 'Tulsa'
    team_labels['UAB Blazers'] = 'UAB'
    team_labels['UC Davis Aggies'] = 'UC-Davis'
    team_labels['UC Irvine Anteaters'] = 'UC-Irvine'
    team_labels['UC Riverside Highlanders'] = 'UC-Riverside'
    team_labels['UC San Diego Tritons'] = 'UC-San Diego'
    team_labels['UC Santa Barbara Gauchos'] = 'UCSB'
    team_labels['UCLA Bruins'] = 'UCLA'
    team_labels['UNC Asheville Bulldogs'] = 'UNC Asheville'
    team_labels['UNC Greensboro Spartans'] = 'UNC Greensboro'
    team_labels['UNC Wilmington Seahawks'] = 'UNC Wilmington'
    team_labels['UT Arlington Mavericks'] = 'UT Arlington'
    team_labels['Utah State Aggies'] = 'Utah State'
    team_labels['Utah Tech Trailblazers'] = 'Utah Tech'
    team_labels['Utah Utes'] = 'Utah'
    team_labels['Utah Valley Wolverines'] = 'Utah Valley'
    team_labels['UTEP Miners'] = 'UTEP'
    team_labels['UTSA Roadrunners'] = 'UTSA'
    team_labels['Valparaiso Beacons'] = 'Valparaiso'
    team_labels['Vanderbilt Commodores'] = 'Vanderbilt'
    team_labels['Vermont Catamounts'] = 'Vermont'
    team_labels['Villanova Wildcats'] = 'Villanova'
    team_labels['Virginia Cavaliers'] = 'Virginia'
    team_labels['Virginia Commonwealth Rams'] = 'VCU'
    team_labels['Virginia Military Institute Keydets'] = 'VMI'
    team_labels['Virginia Tech Hokies'] = 'Virginia Tech'
    team_labels['Wagner Seahawks'] = 'Wagner'
    team_labels['Wake Forest Demon Deacons'] = 'Wake Forest'
    team_labels['Washington Huskies'] = 'Washington'
    team_labels['Washington State Cougars'] = 'Washington State'
    team_labels['Weber State Wildcats'] = 'Weber State'
    team_labels['West Virginia Mountaineers'] = 'West Virginia'
    team_labels['Western Carolina Catamounts'] = 'Western Carolina'
    team_labels['Western Illinois Leathernecks'] = 'Western Illinois'
    team_labels['Western Kentucky Hilltoppers'] = 'Western Kentucky'
    team_labels['Western Michigan Broncos'] = 'Western Michigan'
    team_labels['Wichita State Shockers'] = 'Wichita State'
    team_labels['William & Mary Tribe'] = 'William & Mary'
    team_labels['Winthrop Eagles'] = 'Winthrop'
    team_labels['Wisconsin Badgers'] = 'Wisconsin'
    team_labels['Wofford Terriers'] = 'Wofford'
    team_labels['Wright State Raiders'] = 'Wright State'
    team_labels['Wyoming Cowboys'] = 'Wyoming'
    team_labels['Xavier Musketeers'] = 'Xavier'
    team_labels['Yale Bulldogs'] = 'Yale'  
    team_labels['Youngstown State Penguins'] = 'Youngstown State'

    ## Change school labels to the same team labels in opp_team_id
    df['school'] = df['school'].map(team_labels)

    return df


### Create game_id 
def create_game_id(df): 
    """
    Input df and get back df with game id 

    Dataframe includes duplicate games with columns switched between 'school' and 'opp_team_id' 

    :param - df 
    :return - df with game_id
    """
    ## Create game_id 
    # Best way could be to make a dictionary, where each team is given a number 
    # create a list that includes both 'school' and 'opp_team_id' to include opponents that we don't keep track of

    # create unique team list
    unique_teams = pd.concat([pd.Series(df['school'].unique()), 
                              pd.Series(df['opp_team_id'].unique())])  # create list of unique labels in 'school' column
    unique_teams = unique_teams.unique() # get unique list

    # Create team/id dictionary of key/value pairs 
    team_keys = {}
    i = 1
    for team in unique_teams:
        team_keys[team] = str(i)
        i += 1

    # Create date/id dictionary of key/value pairs  
    date_keys = {}
    i = 1
    for day in df['date'].unique():
        date_keys[day] = str(i)
        i += 1

    matchup_id = [] # create list to hold game_ids

    # loop through 'school', 'opp_team_id' and 'date' column of df
    for a, b, c in zip(df['school'], df['opp_team_id'], df['date']):
        if a < b: # keep alphabetical order of teams
            matchup_id.append(team_keys[a] + team_keys[b] + date_keys[c]) # append strings as id
        else:
            matchup_id.append(team_keys[b] + team_keys[a] + date_keys[c])

    # Create new column in df
    df['game_id'] = matchup_id

    return df


# Create game location dummy variables 
def make_location_dumb(df):
    """
    Input data frame, return dataframe with game_location as two dummies: 
        home, away, with neutral being 0's in both columns

    :param - df 
    :return - df with dummies for game location 
    """

    # Create dummies for game_location
    df = pd.get_dummies(df, columns=['game_location'], drop_first=False)

    # Rename columns
    df = df.rename(columns={'game_location_@': 'away', 
                     'game_location_N': 'neutral',
                     'game_location_h': 'home'})
    
    df = df.drop('neutral', axis=1)

    # return df with dummy columns 'home' and 'away'
    return df



# Correct data type 
def correct_type(df, types=type_map2): 
    """
    Input dataframe, get back df with correct data types

    :param - df 
    :return - df with correct data types 
    """
    df = df.astype(types)

    return df




# Master function
def clean_data(df, add_sos:bool): 
    """
    Input dataframe, get back data frame with clean labels, game ids, 
    and game location dummy variables 

    :param - df 
    :return - clean df
    """

    # Remove NAs 
    df = df.dropna()

    # Match labels 
    df = match_labels(df)

    # Add srs and sos 
    with open('season_srs_dict.json', 'r', encoding='UTF-8') as srs_dict:
        season_srs_dict = json.load(srs_dict)

    for key, value in season_srs_dict.items():
        df.loc[df['school'] == key, 'srs'] = value

    if add_sos:
        with open('season_sos_dict.json', 'r', encoding='UTF-8') as sos_dict:
            season_sos_dict = json.load(sos_dict)

        for key, value in season_sos_dict.items():
            df.loc[df['school'] == key, 'sos'] = value

    # Correct data types 
    df = correct_type(df)

    # Create game ids 
    df = create_game_id(df)

    #Create game location dummy variables 
    df = make_location_dumb(df)

    return df
