# Table column data types

type_map = {"opp_team_id": str,
            "game_result": int, 
            "pts": int,
            "opp_pts": int,
            "fg": int,
            "fga": int,
            "fg_pct": float,
            "fg3": int,
            "fg3a": int,
            "fg3_pct": float,
            "ft": int,
            "fta": int,
            "ft_pct": float,
            "orb": int,
            "trb": int,
            "ast": int,
            "stl": int,
            "blk": int,
            "tov": int,
            "pf": int,
            "opp_fg": int,
            "opp_fga": int,
            "opp_fg_pct": float,
            "opp_fg3": int,
            "opp_fg3a": int,
            "opp_fg3_pct": float,
            "opp_ft": int,
            "opp_fta": int,
            "opp_ft_pct": float,
            "opp_orb": int,
            "opp_trb": int,
            "opp_ast": int,
            "opp_stl": int,
            "opp_blk": int, 
            "opp_tov": int,
            "opp_pf": int,
            "school": str,
            "game_location": str,
            "srs": float,
            "game": int,
            "overtimes": int,
            "streak": int,
            "wins": int,
            "losses": int,
            }


type_map2 = {'game': int,
           'game_result': int, 
           'date': str, 
           'game_location': str,
           'school': str, 
           'opp_team_id': str, 
           'pace': float,
           'ftr': float,
           '3par': float, 
           'ts_perc': float, 
           'trb_perc': float, 
           'ast_perc': float,
           'stl_perc': float, 
           'blk_perc': float,
           'efg_perc': float,
           'tov_perc': float,
           'orb_perc': float,
           'ft_fga': float,
           'srs':float,
           'sos':float,
           'overtimes': int,
           'wins': int,
           'losses': int,
           'streak': int,}


columns = ['game',
           'game_result', 
           'date', 
           'game_location',
           'school', 
           'opp_team_id',
           'pts',
           'opp_pts', 
           'ortg', 
           'drtg', 
           'pace',
           'ftr',
           '3par', 
           'ts_perc', 
           'trb_perc', 
           'ast_perc',
           'stl_perc', 
           'blk_perc',
           'efg_perc',
           'tov_perc',
           'orb_perc',
           'ft_fga',
           'srs',
           'overtimes',
           'wins',
           'losses',
           'streak',]